########################################################################################################################
#
#                                       Common parameters
#
#########################################################################################################################
# Having base dir will allow to move up and down to the directory or scripts, also able to used different settings of
# the pipeline.
BASE_DIR: "/home/Snakemake_DNASeq_Pipeline"
# List of samples containing runID, readgroupd, path to Fastq1 and Fastq2
MASTER_LIST: "/home/Snakemake_DNASeq_Pipeline/master_list.txt"
# Global job name WGS or WES
G_NAME: "WES"

########################################################################################################################
#
#                                       Path to location of programs
#
#########################################################################################################################


########################################################################################################################
#
#                                       Genome reference files
#
#########################################################################################################################
# For the best practices short variant discovery geonme, exome and targeted sequencing, I use GATK resource bundle which
# is a collection of standard files working for human genome sequencing using GATK tools. Download the GATK bundle dir for
# human genome grch37 using following link: https://gatk.broadinstitute.org/hc/en-us/articles/360035890811-Resource-bundle

# Gatk bundle dir for b37 genome version, change the location for dir according to path of home directory
#BUNDLE_DIR: "/home/GATK_Bundle/b37"
# Reference sequence (standard 1000 Genomes fasta), along with fai and dict files
# dbSNP in VCF
# HapMap genotypes and sites VCFs
# OMNI 2.5 genotypes for 1000 Genomes samples, as well as sites, VCF
# The latest set from 1000G phase 3 (v4) for genotype refinement
REF: "/home/GATK_Bundle/b37/human_g1k_v37_decoy.fasta"
MILLS_1KG_GOLD: "/home/GATK_Bundle/b37/Mills_and_1000G_gold_standard.indels.b37.vcf"
PHASE1_INDELS: "/home/GATK_Bundle/b37/1000G_phase1.indels.b37.vcf"
PHASE1_SNPS: "/home/GATK_Bundle/b37/1000G_phase1.snps.high_confidence.b37.vcf"
DBSNP: "/home/GATK_Bundle/b37/dbsnp_138.b37.vcf"
DBSNP129: "/home/GATK_Bundle/b37/dbsnp_138.b37.excluding_sites_after_129.vcf"
OMNI: "/home/GATK_Bundle/b37/1000G_omni2.5.b37.vcf "
HAPMAP: "/home/GATK_Bundle/b37/hapmap_3.3.b37.vcf"
AF_ONLY_GNOMAD: "/home/GATK_Bundle/b37/af-only-gnomad.biallelic.b37.vcf.gz"

########################################################################################################################
#
#                                       GATK settings and parameters
#
#########################################################################################################################

# Intervals file for exome sequencing
# Intervals files are actually subsets of the genomic region which restrict GATK to operate on a subset of geonmics regions.
# An empty or blank string will automatically disable the parameter if you are running WGS data.

INTERVALS: "-L /home/Snakemake_DNASeq_Pipeline/intervals.interval_list"
T_INTERVALS: "/home/Snakemake_DNASeq_Pipeline/intervals.interval_list"
B_INTERVALS: "/home/Snakemake_DNASeq_Pipeline/intervals.interval_list"

# Padding, a parameter used in the interval padding in GATK

PADDING: 100

